// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/playture/backend/internal/infrastructure/godotenv"
	"github.com/playture/backend/internal/infrastructure/postgresql"
	"github.com/playture/backend/internal/infrastructure/redis"
	"log/slog"
)

// Injectors from wire.go:

func wireApp(env *godotenv.Env, logger *slog.Logger, postgresql2 *postgresql.Postgres, rdis *redis.Redis) *Boot {
	boot := NewBoot(env, logger, rdis, postgresql2)
	return boot
}
